/**
 * @fileoverview SMD3 integrity regressions with an independent liblz4 fixture.
 * @author InitSysRev
 */
import { strict as assert } from 'node:assert';
import { deflateSync } from 'node:zlib';
import { parseSmd3, BLOCK_COUNT, HEADER_SIZE, SEGMENT_SECTOR,
  readIcoSideNormals, posToIndex } from '../src/smd3/Smd3Parser.js';
import { writeSmd3, emptySegment, emptySmd3File, setBlock } from '../src/smd3/Smd3Writer.js';
import { decodeLz4Block, encodeLz4Block } from '../src/smd3/Lz4Block.js';

/** @param type Storage type. @param payload Encoded body. @param version Segment version. @returns A single-slot independent fixture. */
function fixture(type: number, payload: Buffer, version = 7): Buffer {
  const output = Buffer.alloc(HEADER_SIZE + SEGMENT_SECTOR);
  output[0] = 7;
  const index = 8 + 8 * 16 + 8 * 256;
  output.writeInt16BE(1, 4 + index * 4);
  output.writeUInt16BE(22 + payload.length, 6 + index * 4);
  output[HEADER_SIZE] = version;
  output[HEADER_SIZE + 21] = type;
  payload.copy(output, HEADER_SIZE + 22);
  return output;
}
/** @param data Compressed bytes. @param declared Declared size. @returns Payload prefixed by its int32 length. */
function compressedPayload(data: Buffer, declared = data.length): Buffer {
  const header = Buffer.alloc(4); header.writeInt32BE(declared);
  return Buffer.concat([header, data]);
}

describe('Audit: SMD3 integrity', () => {
  it('editing an empty segment changes only one independent block and survives stale counts', () => {
    const segment = emptySegment();
    segment.blocks[0].type = 5;
    assert.equal(segment.blocks[1].type, 0);
    assert.equal(segment.blockCount, 0);
    const decoded = parseSmd3(writeSmd3({ ...emptySmd3File(), segments: [segment] }));
    assert.equal(decoded.segments[0].blockCount, 1);
    assert.equal(decoded.segments[0].blocks[0].type, 5);
  });
  it('setBlock copies input and repairs stale counts', () => {
    const segment = emptySegment();
    const block = { type: 5, hp: 7, active: true, orientation: 3 };
    setBlock(segment, 1, 2, 3, block);
    block.type = 9;
    assert.equal(segment.blocks[posToIndex(1, 2, 3)].type, 5);
    assert.equal(segment.blockCount, 1);
  });
  it('preserves all six extra bits, including the signed high bit', () => {
    const segment = emptySegment();
    segment.blocks[42] = { type: 7, hp: 127, active: true, orientation: 31, extra: 63 };
    const decoded = parseSmd3(writeSmd3({ ...emptySmd3File(), segments: [segment] }));
    assert.deepEqual(decoded.segments[0].blocks, segment.blocks);
  });
  it('uses the little-endian raw LZ4 layout from an independent liblz4 fixture', () => {
    // Generated by liblz4 LZ4_compress_default from LE word 0xfc102005 + 131068 zero bytes.
    const compressed = Buffer.from('5f052010fc000100' + 'ff'.repeat(513) + 'e4500000000000', 'hex');
    for (const declared of [compressed.length, 22]) {
      const segment = parseSmd3(fixture(1, compressedPayload(compressed, declared))).segments[0];
      assert.deepEqual(segment.blocks[0], { type: 5, hp: 1, active: true, orientation: 0, extra: 63 });
      assert.equal(segment.blockCount, 1);
    }
  });
  it('preserves version 6 fields when explicitly requested', () => {
    const segment = emptySegment();
    segment.blocks[10] = { type: 2047, hp: 127, active: true, orientation: 31 };
    const encoded = writeSmd3({ ...emptySmd3File(), segments: [segment] }, 6);
    assert.deepEqual(parseSmd3(encoded).segments[0].blocks, segment.blocks);
    segment.blocks[10].extra = 1;
    assert.throws(() => writeSmd3({ ...emptySmd3File(), segments: [segment] }, 6), /extra/);
  });
  it('never shares SINGLE block objects', () => {
    const word = Buffer.alloc(4); word.writeUInt32BE(5);
    const segment = parseSmd3(fixture(3, word)).segments[0];
    segment.blocks[0].type = 7;
    assert.equal(segment.blocks[1].type, 5);
  });
  it('requires real clipping context for SINGLE_SIDE_EDGE and clips correctly', () => {
    const word = Buffer.alloc(4); word.writeUInt32BE(5);
    assert.throws(() => parseSmd3(fixture(5, word)), /icoSideNormals/);
    const asset = Buffer.alloc(36);
    asset.writeFloatBE(1, 0); asset.writeFloatBE(1, 16); asset.writeFloatBE(1, 32);
    const segment = parseSmd3(fixture(5, word), { icoSideNormals: readIcoSideNormals(asset) }).segments[0];
    assert.equal(segment.blockCount, 15 ** 3);
    assert.equal(segment.blocks[posToIndex(16, 17, 17)].type, 0);
    assert.equal(segment.blocks[posToIndex(17, 17, 17)].type, 5);
  });
  it('rejects sector overflow instead of silently truncating compressed data', () => {
    const segment = emptySegment();
    let seed = 123456789;
    for (let i = 0; i < BLOCK_COUNT; i++) {
      seed ^= seed << 13; seed ^= seed >>> 17; seed ^= seed << 5;
      segment.blocks[i] = { type: seed & 8191, hp: (seed >>> 13) & 127,
        active: !!(seed & 0x100000), orientation: (seed >>> 21) & 31, extra: seed >>> 26 };
    }
    assert.throws(() => writeSmd3({ ...emptySmd3File(), segments: [segment] }), /sector capacity/);
  });
  it('rejects colliding region positions and invalid block fields', () => {
    const segment = emptySegment();
    assert.throws(() => writeSmd3({ ...emptySmd3File(), segments: [segment, emptySegment(512, 0, 0)] }), /Duplicate/);
    segment.blocks[0].type = 8192;
    assert.throws(() => writeSmd3({ ...emptySmd3File(), segments: [segment] }), /block type/);
  });
  it('rejects a truncated three-byte payload instead of inventing air', () => {
    const compressed = deflateSync(Buffer.from([5, 0, 0]));
    assert.throws(() => parseSmd3(fixture(1, compressedPayload(compressed), 6)), /Truncated three-byte/);
  });
  it('enforces declared slot boundaries even when more file bytes follow', () => {
    const bytes = fixture(1, compressedPayload(deflateSync(Buffer.alloc(BLOCK_COUNT * 3))), 6);
    const index = 8 + 8 * 16 + 8 * 256;
    bytes.writeUInt16BE(26, 6 + index * 4);
    assert.throws(() => parseSmd3(bytes), /compressed SMD3 length/);
  });
  it('reports recovery omissions and forbids writing an incomplete result', () => {
    const recovered = parseSmd3(fixture(99, Buffer.alloc(0)), { mode: 'recover' });
    assert.equal(recovered.complete, false);
    assert.equal(recovered.diagnostics?.length, 1);
    assert.throws(() => writeSmd3(recovered), /incomplete/);
  });
  it('enforces segment budgets and palette validation', () => {
    assert.throws(() => parseSmd3(fixture(2, Buffer.alloc(0)), { maxSegments: 0 }), /budget/);
    const palette = Buffer.alloc(8); palette.writeInt32BE(32); palette.writeInt32BE(1, 4);
    assert.throws(() => parseSmd3(fixture(4, palette)), /palette header/);
  });
  it('bounded LZ4 rejects invalid offsets and never silently pads output', () => {
    assert.throws(() => decodeLz4Block(Buffer.from([0, 0, 0]), 20), /distance/);
    assert.throws(() => decodeLz4Block(Buffer.from([0xf0]), 20), /Truncated/);
    for (const size of [1, 5, 12, 16, 255, 4096, 131072]) {
      const source = Buffer.alloc(size, 42);
      assert.deepEqual(decodeLz4Block(encodeLz4Block(source), size).data, source);
    }
  });
});
