/**
 * @fileoverview Complete blueprint inventories, lossless documents and ZIP/folder exports.
 * References: StarMade-Open decf3a1, BlueprintEntry.export/writeMeta/writeHeader,
 * SegmentDataFileUtils.getSegFile and SegmentBufferManager.getBufferCoordAbsolute.
 * Original files are retained independently from the mutable domain model.
 */
import { isDeepStrictEqual } from 'node:util';
import path from 'node:path';
import { DecodeError } from '../core/DecodeError.js';
import { writeTo, TagDocument } from '../core/TagParser.js';
import { BlueprintArchive, BlueprintEntity, BlueprintHeader, parseSmbph } from './SmentParser.js';
import type { SmentEntity } from './SmentParser.js';
import { BlueprintMeta, parseSmbpm, getSmbpmInternals, renameRailChild, copySmbpmWithInternals } from './SmbpmParser.js';
import { BlueprintLogic, parseSmbpl } from './SmbplParser.js';
import { writeSmbph } from './SmbphWriter.js';
import { writeSmbpm } from './SmbpmWriter.js';
import { writeSmbpl } from './SmbplWriter.js';
import { writeSmd3 } from './Smd3Writer.js';
import { BLOCK_COUNT } from './Smd3Parser.js';
import type { Smd3File } from './Smd3Parser.js';
import { Smd3Document } from './Smd3Document.js';
import { BlueprintReadContext } from './BlueprintReadContext.js';
import type { BlueprintParseOptions } from './BlueprintReadContext.js';
import { BlueprintZip, createBlueprintZip } from './BlueprintZip.js';
import { readBlueprintFiles, writeBlueprintFiles } from './BlueprintFiles.js';
import type { BlockConfig } from '../config/BlockConfig.js';
import type { BlockPosition } from '../objects/ElementPosition.js';
import { BlockVolume } from './BlockVolume.js';
import { BlueprintModel } from './BlueprintModel.js';

/** Files use ZIP paths including the blueprint root; null represents a directory. */
export type BlueprintFileMap = ReadonlyMap<string, Buffer | null>;

/** Output uses the same finite resource limits as input; replacement is explicit. */
export interface BlueprintWriteOptions extends BlueprintParseOptions {
  overwrite?: boolean;
}

/** A source region keeps its original name and physical sector layout. */
interface RegionSource { path: string; document: Smd3Document; }

/** Persisted fields are snapshotted separately from derived presentation fields. */
interface EntitySource {
  path: string;
  children: Set<string>;
  header: unknown;
  meta: unknown;
  logic: unknown;
  manager: Buffer;
  thrust: Buffer;
  managerRaw?: Uint8Array | null;
  thrustRaw?: Uint8Array | null;
  aiPresent: boolean;
  regions: Map<Smd3File, RegionSource>;
}

/** One current entity and the corresponding original entity, when available. */
interface LocatedEntity { path: string; entity: SmentEntity; source?: EntitySource; }

/** Serializes observable data without relying on object identity or dirty flags. */
function snapshot(value: unknown): unknown { return structuredClone(value); }

/** Snapshots the actual tag generated by a metadata component, including hidden slots. */
function component(value: BlueprintMeta['manager'] | BlueprintMeta['thrustConfig']): Buffer {
  return value ? writeTo(value.toTag()) : Buffer.alloc(0);
}

/** Includes hidden persistence flags and component tags in metadata change detection. */
function metadataSnapshot(meta: BlueprintMeta | null): unknown {
  if (!meta) return snapshot(null);
  return snapshot({ ...meta, manager: component(meta.manager), thrustConfig: component(meta.thrustConfig),
    internals: getSmbpmInternals(meta) });
}

/** Validates one path component; nested entity names are reserved ATTACHED_N names. */
function checkName(name: string, child: boolean): void {
  if (!name || name === '.' || name === '..' || /[\\/\0:]/.test(name) ||
      (child && !/^ATTACHED_\d+$/.test(name))) {
    throw new DecodeError('E_FORMAT', 'Invalid blueprint entity name', { path: name });
  }
}

/** Uses Java arithmetic shifts, including negative region coordinates. */
function regionKey(file: Smd3File, sourcePath = ''): string {
  const s = file.segments[0];
  const coordinates = /\.(-?\d+)\.(-?\d+)\.(-?\d+)\.smd3$/.exec(sourcePath);
  return s ? [s.x, s.y, s.z].map(v => ((v >> 5) + 8) >> 4).join('.')
    : coordinates ? coordinates.slice(1).map(Number).join('.') : '0.0.0';
}

/** A document owns original bytes and exposes an editable complete blueprint tree. */
export class BlueprintDocument {
  readonly archive: BlueprintArchive;
  private readonly original: Map<string, Buffer | null>;
  private readonly sources = new Map<string, EntitySource>();
  private readonly byEntity = new WeakMap<SmentEntity, EntitySource>();
  private readonly extraEdits = new Map<string, Buffer | undefined>();
  private readonly rootName: string;

  /** Captures a validated file inventory and parses all modelled resources. */
  private constructor(entries: BlueprintFileMap, private readonly options: BlueprintParseOptions,
    private readonly zip?: BlueprintZip) {
    this.options = { ...options, segmentOptions: { ...options.segmentOptions } };
    this.original = new Map([...entries].map(([p, b]) => [p, b === null ? null : Buffer.from(b)]));
    const context = new BlueprintReadContext(options);
    if (context.mode !== 'strict') throw new DecodeError('E_INCOMPLETE', 'Editable blueprint documents require strict parsing');
    const roots = [...entries.keys()].filter(p => /^[^/]+\/header\.smbph$/.test(p));
    if (roots.length !== 1) throw new DecodeError('E_FORMAT', 'Exactly one blueprint root header is required');
    this.rootName = roots[0].split('/')[0];
    checkName(this.rootName, false);
    const children = new Map<string, Set<string>>([[this.rootName, new Set()]]);
    const regions = new Map<string, string[]>();
    for (const [p, data] of this.original) {
      context.chargeFile();
      if (!p.startsWith(this.rootName + '/')) throw new DecodeError('E_FORMAT', 'Entry outside blueprint root', { path: p });
      if (data !== null) context.chargeBytes(data.length);
      const parts = p.slice(this.rootName.length + 1).split('/');
      let parent = this.rootName, i = 0;
      while (i < parts.length - 1 && /^ATTACHED_\d+$/.test(parts[i])) {
        const child = `${parent}/${parts[i++]}`;
        children.get(parent)!.add(child);
        if (!children.has(child)) children.set(child, new Set());
        if (i > context.maxDepth || children.size > context.maxEntities) throw new DecodeError('E_LIMIT', 'Blueprint entity/depth budget exceeded');
        parent = child;
      }
      if (parts.length === i + 2 && parts[i] === 'DATA' && /\.smd[0-3]$/.test(parts[i + 1])) {
        if (!p.endsWith('.smd3')) throw new DecodeError('E_UNSUPPORTED', 'Legacy segment resources require explicit migration', { path: p });
        if (!regions.has(parent)) regions.set(parent, []);
        regions.get(parent)!.push(p);
      }
    }
    let blocks = 0;
    /** Decodes one entity with operation-wide node, byte and block budgets. */
    const readEntity = (p: string, depth: number, world: { x: number; y: number; z: number },
      offset: { x: number; y: number; z: number }): BlueprintEntity => {
      context.enterEntity(depth);
      const headerBytes = this.original.get(`${p}/header.smbph`);
      if (!headerBytes) throw new DecodeError('E_FORMAT', 'Missing blueprint entity header', { path: p });
      const metaBytes = this.original.get(`${p}/meta.smbpm`), logicBytes = this.original.get(`${p}/logic.smbpl`);
      const meta = metaBytes ? parseSmbpm(metaBytes, context.tagOptions) : null;
      const logic = logicBytes ? parseSmbpl(logicBytes) : null;
      const regionSources = new Map<Smd3File, RegionSource>();
      for (const name of regions.get(p) ?? []) {
        const bytes = this.original.get(name);
        const document = new Smd3Document(bytes!, { ...options.segmentOptions, maxBlocks: context.maxBlocks - blocks });
        blocks += document.file.usedSlots * BLOCK_COUNT;
        regionSources.set(document.file, { path: name, document });
      }
      const entity = new BlueprintEntity({ name: p.substring(p.lastIndexOf('/') + 1),
        header: parseSmbph(headerBytes), meta, logic, offset, worldOffset: world,
        segments: [...regionSources.keys()], children: [] });
      for (const child of children.get(p)!) {
        const o = meta?.childOffsetFor(child) ?? { x: 0, y: 0, z: 0 };
        entity.children.push(readEntity(child, depth + 1,
          { x: world.x + o.x, y: world.y + o.y, z: world.z + o.z }, o));
      }
      const source: EntitySource = { path: p, children: new Set(entity.children.map(c => c.name)), header: snapshot(entity.header),
        meta: metadataSnapshot(meta), logic: snapshot(logic), manager: component(meta?.manager ?? null),
        thrust: component(meta?.thrustConfig ?? null), aiPresent: meta?.aiConfig != null,
        managerRaw: meta && getSmbpmInternals(meta).managerRaw, thrustRaw: meta && getSmbpmInternals(meta).thrustRaw,
        regions: regionSources };
      this.sources.set(p, source); this.byEntity.set(entity, source);
      return entity;
    };
    this.archive = new BlueprintArchive(readEntity(this.rootName, 0, { x: 0, y: 0, z: 0 }, { x: 0, y: 0, z: 0 }));
  }

  /** Reads an archive, retaining ZIP metadata, compressed entries and all ancillary files. */
  static fromSment(data: Buffer | Uint8Array, options: BlueprintParseOptions = {}): BlueprintDocument {
    const zip = new BlueprintZip(data, options);
    return new BlueprintDocument(zip.getEntries(), options, zip);
  }

  /** Snapshots a folder in memory; no later export depends on the source directory. */
  static fromFolder(folderPath: string, options: BlueprintParseOptions = {}): BlueprintDocument {
    return new BlueprintDocument(readBlueprintFiles(folderPath, options), options);
  }

  /** Builds a document from a complete caller-created model using the canonical writers. */
  static fromArchive(archive: BlueprintArchive, options: BlueprintParseOptions = {}): BlueprintDocument {
    return BlueprintDocument.fromSment(createBlueprintZip(renderArchive(archive, options), options), options);
  }

  /** Provides the editable root; offsets and aggregate counters are derived views. */
  get root(): BlueprintEntity { return this.archive.root; }

  /** Opens a live block grid, retaining source region names, empty allocations and document bytes. */
  blocks(entity: SmentEntity = this.root, config?: Pick<BlockConfig, 'getById'>): BlockVolume {
    const located = locate(this.archive, this.options, (candidate, p) => this.byEntity.get(candidate) ?? this.sources.get(p))
      .find(item => item.entity === entity);
    if (!located) throw new DecodeError('E_RANGE', 'Entity does not belong to this blueprint document');
    const regionCoordinates = new Map<Smd3File, BlockPosition>();
    for (const [file, source] of located.source?.regions ?? []) {
      const [x, y, z] = regionKey(file, source.path).split('.').map(Number);
      regionCoordinates.set(file, { x, y, z });
    }
    return new BlockVolume(entity.segments, { config, regionCoordinates,
      maxSegments: Math.floor((this.options.maxBlocks ?? 16 * 1024 * 1024) / BLOCK_COUNT) });
  }

  /** Bounded hierarchy with instance-scoped block definitions and per-entity live grids. */
  model(config?: Pick<BlockConfig, 'getById'>): BlueprintModel {
    return new BlueprintModel(this.archive, { config, maxEntities: this.options.maxEntities,
      maxDepth: this.options.maxDepth, maxSegments: Math.floor((this.options.maxBlocks ?? 16 * 1024 * 1024) / BLOCK_COUNT) },
    entity => this.blocks(entity, config));
  }

  /** Returns detached current file contents, including unknown files and empty directories. */
  get files(): Map<string, Buffer | null> { return this.toFiles(); }

  /** Adds or replaces an ancillary file using a path relative to the blueprint root. */
  setFile(relativePath: string, data: Buffer | Uint8Array): this {
    this.checkExtraPath(relativePath);
    this.extraEdits.set(relativePath, Buffer.from(data));
    return this;
  }

  /** Removes an ancillary file; modelled resources must be edited through the tree. */
  removeFile(relativePath: string): this {
    this.checkExtraPath(relativePath);
    this.extraEdits.set(relativePath, undefined);
    return this;
  }

  /** Prevents raw-file edits from silently overriding the editable domain model. */
  private checkExtraPath(p: string): void {
    if (!p || /[\\\0:]/.test(p) || p.split('/').some(s => !s || s === '.' || s === '..')) {
      throw new DecodeError('E_FORMAT', 'Unsafe blueprint resource path', { path: p });
    }
    if (/^(?:ATTACHED_\d+\/)*(?:header\.smbph|meta\.smbpm|logic\.smbpl|DATA\/[^/]+\.smd[0-3])$/.test(p)) {
      throw new DecodeError('E_FORMAT', 'Edit modelled resources through the blueprint tree', { path: p });
    }
  }

  /** Renders only changed resources, preserving original bytes for all others. */
  toFiles(options: BlueprintParseOptions = {}): Map<string, Buffer | null> {
    return this.renderFiles(options, this.root.name);
  }

  /** Rebinds a folder's root name without mutating the caller's model. */
  private renderFiles(options: BlueprintParseOptions, rootName: string): Map<string, Buffer | null> {
    const limits = { ...this.options, ...options };
    const archive = { root: new BlueprintEntity({ ...this.root, name: rootName }), diagnostics: this.archive.diagnostics };
    const located = locate(archive, limits, (entity, p) => this.byEntity.get(entity) ??
      this.sources.get(this.rootName + p.slice(rootName.length)));
    const moved = new Map(located.filter(e => e.source).map(e => [e.source!.path, e.path]));
    const entries = new Map<string, Buffer | null>();
    for (const [p, data] of this.original) {
      const owner = ownerPath(p);
      const target = moved.get(owner);
      if (target !== undefined) entries.set(target + p.slice(owner.length), data === null ? null : Buffer.from(data));
    }
    for (const [p, data] of this.extraEdits) {
      const name = `${rootName}/${p}`;
      if (data !== undefined && !located.some(e => e.path === ownerPath(name))) throw new DecodeError('E_FORMAT', 'Ancillary file belongs to a missing entity', { path: p });
      if (data === undefined) entries.delete(name); else entries.set(name, Buffer.from(data));
    }
    renderEntities(located, entries, moved);
    checkOutput(entries, limits);
    return entries;
  }

  /** Returns the exact original ZIP when unchanged, otherwise reuses intact ZIP records. */
  toBuffer(options: BlueprintParseOptions = {}): Buffer {
    const entries = this.toFiles(options), limits = { ...this.options, ...options };
    return this.zip ? this.zip.toBuffer(entries, limits.maxInputBytes) : createBlueprintZip(entries, limits);
  }

  /** Publishes a staged directory; replacing an existing destination requires overwrite. */
  writeFolder(targetDirectory: string, options: BlueprintWriteOptions = {}): void {
    const name = path.basename(path.resolve(targetDirectory));
    writeBlueprintFiles(this.renderFiles(options, name), targetDirectory, name, { ...this.options, ...options });
  }
}

/** Finds the owning entity, stopping at ancillary directories such as DATA. */
function ownerPath(p: string): string {
  const parts = p.split('/'); let i = 1;
  while (i < parts.length - 1 && /^ATTACHED_\d+$/.test(parts[i])) i++;
  return parts.slice(0, i).join('/');
}

/** Traverses the current tree once, rejecting cycles, duplicate names and partial models. */
function locate(archive: Pick<BlueprintArchive, 'root' | 'diagnostics'>, options: BlueprintParseOptions,
  source: (entity: SmentEntity, path: string) => EntitySource | undefined): LocatedEntity[] {
  if (archive.diagnostics.length) throw new DecodeError('E_INCOMPLETE', 'Cannot write recovered blueprint data');
  const context = new BlueprintReadContext(options), seen = new Set<SmentEntity>(), paths = new Set<string>();
  const result: LocatedEntity[] = []; let blocks = 0;
  /** Visits a single entity only once, with bounded recursion. */
  const visit = (entity: SmentEntity, parent: string, depth: number): void => {
    context.enterEntity(depth); checkName(entity.name, depth > 0);
    const p = parent + entity.name;
    if (seen.has(entity) || paths.has(p)) throw new DecodeError('E_FORMAT', 'Cyclic or duplicate blueprint entity', { path: p });
    seen.add(entity); paths.add(p); result.push({ entity, path: p, source: source(entity, p) });
    const positions = new Set<string>();
    for (const file of entity.segments) {
      if (file.complete === false || file.diagnostics?.length) throw new DecodeError('E_INCOMPLETE', 'Cannot write recovered segment data');
      blocks += file.segments.length * BLOCK_COUNT;
      if (blocks > context.maxBlocks) throw new DecodeError('E_LIMIT', 'Blueprint output block budget exceeded');
      for (const segment of file.segments) {
        const key = [segment.x, segment.y, segment.z].join(',');
        if (positions.has(key)) throw new DecodeError('E_FORMAT', 'Duplicate segment position across region files');
        positions.add(key);
      }
    }
    for (const child of entity.children) visit(child, p + '/', depth + 1);
  };
  visit(archive.root, '', 0);
  return result;
}

/** Uses the entity model to update modelled resources without discarding ancillary files. */
function renderEntities(located: LocatedEntity[], entries: Map<string, Buffer | null>, moved: Map<string, string>): void {
  for (const { entity, path: p, source } of located) {
    const meta = prepareMeta(entity, source, moved, p) ?? (source ? null : parseSmbpm(Buffer.from('0000000501', 'hex')));
    const writeModel = (name: string, value: unknown, before: unknown, bytes: () => Buffer): void => {
      const key = `${p}/${name}`;
      if (value === null) entries.delete(key);
      else if (!before || !isDeepStrictEqual(snapshot(value), before)) entries.set(key, bytes());
    };
    const logic = entity.logic ?? (source ? null : new BlueprintLogic({ structureVersion: 0, controllers: [], links: [], controllerCount: 0 }));
    writeModel('logic.smbpl', logic, source?.logic, () => writeSmbpl(logic!));
    const metaKey = `${p}/meta.smbpm`;
    if (!meta) entries.delete(metaKey);
    else if (!source || !isDeepStrictEqual(metadataSnapshot(meta), source.meta)) entries.set(metaKey, writeMetadata(meta, source));
    const regionEntries = new Map<string, Buffer>();
    let changed = !source || entity.segments.length !== source.regions.size;
    for (const file of entity.segments) {
      const original = source?.regions.get(file) ?? (source && [...source.regions].find(([before, original]) => regionKey(before, original.path) === regionKey(file))?.[1]);
      const name = original ? original.path.slice(source!.path.length + 1) : `DATA/${entity.name}.${regionKey(file)}.smd3`;
      const key = `${p}/${name}`;
      if (regionEntries.has(key)) throw new DecodeError('E_FORMAT', 'Duplicate blueprint region filename', { path: key });
      const bytes = original ? original.document.toBuffer(file) : writeSmd3(file);
      changed = changed || !entries.get(key)?.equals(bytes);
      regionEntries.set(key, bytes);
    }
    for (const name of [...entries.keys()]) {
      if (name.startsWith(`${p}/DATA/`) && !name.slice(p.length + 6).includes('/') && name.endsWith('.smd3')) entries.delete(name);
    }
    for (const [key, data] of regionEntries) entries.set(key, data);
    let header = entity.header;
    if (changed) {
      const counts = new Map<number, number>();
      const low = [Infinity, Infinity, Infinity], high = [-Infinity, -Infinity, -Infinity];
      for (const file of entity.segments) for (const segment of file.segments) for (let i = 0; i < segment.blocks.length; i++) {
        const block = segment.blocks[i];
        if (block.type) {
          counts.set(block.type, (counts.get(block.type) ?? 0) + 1);
          const position = [segment.x + (i & 31) - 16, segment.y + ((i >> 5) & 31) - 16, segment.z + (i >> 10) - 16];
          for (let axis = 0; axis < 3; axis++) { low[axis] = Math.min(low[axis], position[axis]); high[axis] = Math.max(high[axis], position[axis]); }
        }
      }
      // SegmentData.updateBBAdd uses an exclusive maximum; SegmentBuffer.updateBB
      // then adds a one-block margin: occupied center min-1 and max+2.
      const boundingBox = counts.size ? { minX: low[0] - 1, minY: low[1] - 1, minZ: low[2] - 1,
        maxX: high[0] + 2, maxY: high[1] + 2, maxZ: high[2] + 2 } : { minX: 0, minY: 0, minZ: 0, maxX: 0, maxY: 0, maxZ: 0 };
      header = new BlueprintHeader({ ...header, totalBlockCount: undefined,
        score: null, boundingBox, blockCountByType: [...counts].map(([type, count]) => ({ type, count })) });
    }
    if (!source || !isDeepStrictEqual(snapshot(header), source.header)) {
      if (header.entityTypeOrdinal < 0) throw new DecodeError('E_UNSUPPORTED', 'Cannot encode unknown blueprint entity type');
      entries.set(`${p}/header.smbph`, writeSmbph(header));
    }
    if (!source && !entries.has(`${p}/modmappings.smbmm`)) entries.set(`${p}/modmappings.smbmm`, Buffer.alloc(0));
  }
}

/** Synchronizes attachment paths and ensures direct component edits reach their writer. */
function prepareMeta(entity: SmentEntity, source: EntitySource | undefined,
  moved: Map<string, string>, path: string): BlueprintMeta | null {
  let meta = entity.meta;
  if (!meta) {
    if (entity.children.some(c => !source?.children.has(c.name))) throw new DecodeError('E_FORMAT', 'New attachments require docking or rail metadata');
    return null;
  }
  if (source && !component(meta.manager).equals(source.manager)) meta = meta.withManager(meta.manager);
  if (source && !component(meta.thrustConfig).equals(source.thrust)) meta = meta.withThrustConfig(meta.thrustConfig);
  if (source?.aiPresent && !meta.aiConfig) meta = meta.withAiConfig(null);
  const names = new Set(entity.children.map(c => c.name));
  const childPaths = new Set([...names].map(name => `${path}/${name}`));
  /** Maps an old attached entity path to its current location, omitting removed children. */
  const reference = (name: string): string | null => {
    const base = name.substring(name.lastIndexOf('/') + 1);
    const old = source ? `${source.path}/${base}` : '';
    const target = moved.get(old);
    if (target && childPaths.has(target)) return target === old ? name : target;
    if (names.has(base)) return `${path}/${base}`;
    if (source?.children.has(base)) return null;
    throw new DecodeError('E_FORMAT', 'Attachment metadata references a missing child', { path: name });
  };
  const docking = meta.dockingEntries.flatMap(d => { const name = reference(d.name); return name === null ? [] : [{ ...d, name }]; });
  const rails = meta.railChildren.flatMap(d => { const name = reference(d.name); return name === null ? [] : [renameRailChild(d, name)]; });
  if (!isDeepStrictEqual(snapshot(docking), snapshot(meta.dockingEntries))) meta = meta.withDockingEntries(docking);
  if (!isDeepStrictEqual(snapshot(rails), snapshot(meta.railChildren))) meta = meta.withRailChildren(rails);
  const references = new Set([...docking, ...rails].map(d => d.name.substring(d.name.lastIndexOf('/') + 1)));
  for (const child of entity.children) {
    if (!references.has(child.name) && !source?.children.has(child.name)) throw new DecodeError('E_FORMAT', 'New attachment has no docking or rail metadata', { path: child.name });
  }
  return meta;
}

/** Preserves component Tag envelopes and opaque extensions after Java's terminal manager Tag. */
function writeMetadata(meta: BlueprintMeta, source?: EntitySource): Buffer {
  if (meta.manager && meta.thrustConfig) throw new DecodeError('E_UNSUPPORTED', 'Manager and standalone thrust Tags cannot share the terminal metadata section');
  const internals = { ...getSmbpmInternals(meta) };
  for (const [kind, value, original, before] of [
    ['manager', meta.manager, source?.managerRaw, source?.manager],
    ['thrust', meta.thrustConfig, source?.thrustRaw, source?.thrust],
  ] as const) {
    if (original && !component(value).equals(before!)) {
      const document = new TagDocument(original);
      if (value) {
        const tag = value.toTag();
        internals[`${kind}Raw`] = document.toBuffer(tag);
        internals[`${kind}Tag`] = tag;
      } else if (document.trailingData.length) {
        throw new DecodeError('E_UNSUPPORTED', 'Removing this component would orphan its opaque trailing metadata');
      }
    }
  }
  return writeSmbpm(copySmbpmWithInternals(meta, internals));
}

/** Checks output resource budgets before ZIP allocation or filesystem staging. */
function checkOutput(entries: BlueprintFileMap, options: BlueprintParseOptions): void {
  const context = new BlueprintReadContext(options);
  for (const data of entries.values()) { context.chargeFile(); if (data !== null) context.chargeBytes(data.length); }
  // Metadata Tags share an aggregate node and nested-inflation allowance on output too.
  for (const [name, data] of entries) {
    if (/^[^/]+\/(?:ATTACHED_\d+\/)*meta\.smbpm$/.test(name) && data !== null) parseSmbpm(data, context.tagOptions);
  }
}

/** Produces all resources for a caller-created blueprint with deterministic region names. */
function renderArchive(archive: Pick<BlueprintArchive, 'root' | 'diagnostics'>, options: BlueprintParseOptions): Map<string, Buffer | null> {
  const entries = new Map<string, Buffer | null>();
  renderEntities(locate(archive, options, () => undefined), entries, new Map());
  checkOutput(entries, options);
  return entries;
}

/** Reads a complete .sment document suitable for lossless editing and export. */
export function readBlueprintDocument(data: Buffer | Uint8Array, options: BlueprintParseOptions = {}): BlueprintDocument {
  return BlueprintDocument.fromSment(data, options);
}

/** Reads all resources from an unpacked blueprint, including ancillary files. */
export function readBlueprintFolderDocument(folderPath: string, options: BlueprintParseOptions = {}): BlueprintDocument {
  return BlueprintDocument.fromFolder(folderPath, options);
}

/** Writes a lossless document or a canonical complete blueprint model as .sment bytes. */
export function writeSment(input: BlueprintDocument | BlueprintArchive, options: BlueprintParseOptions = {}): Buffer {
  return input instanceof BlueprintDocument ? input.toBuffer(options) : createBlueprintZip(renderArchive(input, options), options);
}

/** Writes a complete blueprint folder; targetDirectory is the new root directory itself. */
export function writeBlueprintFolder(input: BlueprintDocument | BlueprintArchive, targetDirectory: string,
  options: BlueprintWriteOptions = {}): void {
  if (input instanceof BlueprintDocument) input.writeFolder(targetDirectory, options);
  else {
    const name = path.basename(path.resolve(targetDirectory));
    const archive = { root: new BlueprintEntity({ ...input.root, name }), diagnostics: input.diagnostics };
    writeBlueprintFiles(renderArchive(archive, options), targetDirectory, name, options);
  }
}
